### ISSUE TITLE
Help with my css 

### ISSUE THREAD

**Issue by Juliebou** [Juliebou/modularity-mindfulness#1]
@anna-pokhilenko
@thatkidmadrid

Good afternoon,
I need help with 2 things:
1. Align my images inside the section so they take up the same space.
2. Getting rid of the white space at the end of my section, before the footer.
thanks,
Julie B.

**Comment by thatkidmadrid** [comment]
Hey Julie,
I think you're on the right track. 

## 1. Align my images inside the section so they take up the same space.

I just think there's some confusion in terms of mixing up columns and rows.

The key to getting the images to line up is to have equal widths because all of the images are the same actual size (600px x 400px). So, as long as the widths are the same, their heights will also be the same and they will align properly.

You're on the right track of setting up a 3-part grid in your `section` but I notice you're using `grid-template-rows` when I think you probably meant to do `grid-template-columns`. making this change ensures that the widths of the columns get the same share (1fr) as defined in the grid you set up in `section`.

## 2. Getting rid of the white space at the end of my section, before the footer
A good way to see what's going on is to use your browser inspector to see where margins and paddings may be affecting your layout

![Screen Shot 2021-09-28 at 3 52 40 PM](https://user-images.githubusercontent.com/6340290/135156371-e12849b3-a637-4559-81f8-ac51d8eb5b78.png)

by default in chrome:
`#f8c79c` orange shows margins
`#c8d8b4` green shows padding

please refer back to the [Boxes & borders cheat sheet](https://learn-the-web.algonquindesign.ca/topics/boxes-borders-cheat-sheet/) for how to select on which sides of a box margins and paddings are placed.

**but a big hint** is that maybe you don't need margins/paddings on the articles. There is an even more convenient way to space out items on a grid. Please refer back to the [CSS grid cheat sheet](https://learn-the-web.algonquindesign.ca/topics/css-grid-cheat-sheet/) to find this property.

**Comment by thatkidmadrid** [comment]
Also, a good way to remember the difference between columns and rows is to think of large stone _**columns**_ like in the [Greek Parthenon](https://en.wikipedia.org/wiki/Parthenon)
![300px-The_Parthenon_in_Athens](https://user-images.githubusercontent.com/6340290/135158618-6edd7e5d-fa25-4826-a07f-5103428c874a.jpg)

The stone **_columns_** run _vertically_ like columns in a **data table** or **layout grid**
