### ISSUE TITLE
How to align the div .text in the center

### ISSUE THREAD

**Issue by Juliebou** [Juliebou/modularity-mindfulness#2]
@anna-pokhilenko
@thatkidmadrid

How can I align the div in the center? I tried all the align-self, align-content, etc. and nothing works. What I am thinking is to bring it into a grid with the section...Let me know what you think.
thank you,
Julie

**Comment by thatkidmadrid** [comment]
Hey Julie,
For both the 608px and 1000px reference screenshots that section is the same size and it doesn't seem to fit on a grid column exactly, so that should be a clue that it's width is probably explicitly defined. More specifically, it probably has a max-width as it changes to fit the contents on the 320px screenshot.

Please refer to the[ CSS Layout Cheat Sheet](https://learn-the-web.algonquindesign.ca/topics/css-layout-cheat-sheet/) for how to center the component once you apply that max-width. There is a example in the section on centering elements that is very applicable for this situation

You're very close!

PS. even past the 1000px reference, your layout should extend fully horizontally, so the max width you set in your last media query can be change to 100% or 100vw (although this is not being checked by markbot)
